version: '2'
services:
    datatooldemo-app:
        image: datatooldemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://datatooldemo-mysql:3306/datatooldemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    datatooldemo-mysql:
        extends:
            file: mysql.yml
            service: datatooldemo-mysql
